#!/usr/bin/env perl

use Search::Elasticsearch;

# Connect to localhost:9200:

my $e = Search::Elasticsearch->new();

# Connect to cluster at search1:9200, sniff all nodes and round-robin between them:

my $e = Search::Elasticsearch->new(
    nodes => 'localhost:9200',
);

if (1 == 1) {
    my $filename = 'town_list';

    open(my $fh, '<:encoding(UTF-8)', $filename)
      or die "Could not open file '$filename' $!";

    my $idx = 1;
    while (my $row = <$fh>) {
      chomp $row;

      $e->index(
          index   => 'rplus-dict',
          type    => 'cities',
          id      => $idx,
          body    => {
              name   => lc $row
          }
      );

      $idx ++;
    }

    print "cities done: count $idx\n";
}

if (1 == 1) {
    my $filename = 'street_list';
    open(my $fh, '<:encoding(UTF-8)', $filename)
      or die "Could not open file '$filename' $!";

    my $idx = 1;
    while (my $row = <$fh>) {
      chomp $row;

      $e->index(
          index   => 'rplus-dict',
          type    => 'streets',
          id      => $idx,
          body    => {
              name   => lc $row
          }
      );

      $idx ++;
    }

    print "streets done: count $idx\n";
}
